import Head from 'next/head'
import Auction from '../components/landing/Auction/Auction'
import Bid from '../components/landing/Bid'
import Category from '../components/landing/Category/Category'
import Hero from '../components/landing/Hero/Hero'
import TopSection from '../components/landing/TopSection/TopSection'
import Trending from '../components/landing/Trending'





export default function Home() {


  return (
    <div>
      <Head>
        <title>Dstage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Hero/>
      <Trending/>
      <TopSection/>
      <Auction/>
      <Bid/>
      <Category/>
      
    </div>
      
  )
}
